# analysis.R
# Statistical analysis of the checkout A/B test.
# Uses base R for the stats (so it runs anywhere) and ggplot2 for charts if
# available. Outputs figures to reports/figures and a summary to reports/summary.md.

suppressWarnings(suppressMessages({
  has_ggplot <- requireNamespace("ggplot2", quietly = TRUE)
}))

df <- read.csv("data/ab_test.csv", stringsAsFactors = FALSE)
dir.create("reports/figures", showWarnings = FALSE, recursive = TRUE)

## ---- 1. Conversion rate: two-proportion z-test ----------------------------
tab <- table(df$group, df$converted)
conv_A <- mean(df$converted[df$group == "A"])
conv_B <- mean(df$converted[df$group == "B"])
lift   <- (conv_B - conv_A) / conv_A

# Treatment first, so prop.test's confidence interval is (B - A) -- matching
# how the difference is reported. Passing A first returns (A - B) and flips
# the interval's sign.
successes <- c(sum(df$converted[df$group == "B"]),
               sum(df$converted[df$group == "A"]))
trials    <- c(sum(df$group == "B"), sum(df$group == "A"))
prop_test <- prop.test(successes, trials, correct = FALSE)

## ---- 2. Revenue per user: Welch's t-test ----------------------------------
rev_A <- df$revenue[df$group == "A"]
rev_B <- df$revenue[df$group == "B"]
t_rev <- t.test(rev_B, rev_A)   # B - A

## ---- 3. Segment check: does device interact with the effect? ---------------
seg <- aggregate(converted ~ group + device, data = df, FUN = mean)

## ---- 4. Charts -------------------------------------------------------------
if (has_ggplot) {
  library(ggplot2)

  conv_df <- data.frame(
    group = c("A (control)", "B (treatment)"),
    rate  = c(conv_A, conv_B)
  )
  p1 <- ggplot(conv_df, aes(group, rate, fill = group)) +
    geom_col(width = 0.6, show.legend = FALSE) +
    geom_text(aes(label = scales::percent(rate, accuracy = 0.1)), vjust = -0.4) +
    scale_y_continuous(labels = scales::percent) +
    labs(title = "Checkout conversion rate by group",
         x = NULL, y = "Conversion rate") +
    theme_minimal(base_size = 13)
  ggsave("reports/figures/conversion_by_group.png", p1, width = 7, height = 4.5, dpi = 130)

  p2 <- ggplot(seg, aes(device, converted, fill = group)) +
    geom_col(position = "dodge") +
    scale_y_continuous(labels = scales::percent) +
    labs(title = "Conversion by device and group",
         x = "Device", y = "Conversion rate", fill = "Group") +
    theme_minimal(base_size = 13)
  ggsave("reports/figures/conversion_by_device.png", p2, width = 7, height = 4.5, dpi = 130)

  p3 <- ggplot(subset(df, revenue > 0), aes(revenue, fill = group)) +
    geom_density(alpha = 0.5) +
    labs(title = "Revenue distribution among converters",
         x = "Revenue per converting user", y = "Density", fill = "Group") +
    theme_minimal(base_size = 13)
  ggsave("reports/figures/revenue_distribution.png", p3, width = 7, height = 4.5, dpi = 130)
}

## ---- 5. Write summary ------------------------------------------------------
summary_md <- sprintf(
"# A/B Test Results

_Auto-generated by `R/analysis.R`._

## Conversion (primary metric)
- Control (A): **%.2f%%**
- Treatment (B): **%.2f%%**
- Relative lift: **%+.1f%%**
- Two-proportion z-test p-value: **%.4g**
- 95%% CI for difference (B - A): [%.4f, %.4f]

## Revenue per user (secondary metric)
- Mean revenue A: **%.2f**, B: **%.2f**
- Welch's t-test p-value: **%.4g**
- 95%% CI for mean difference: [%.2f, %.2f]

## Decision
%s

> The lift is genuine in the data-generating process (control 11.8%% vs
> treatment 13.4%%). With ~8,000 users per arm the test is well powered to
> detect it, which the p-value confirms.
",
conv_A * 100, conv_B * 100, lift * 100,
prop_test$p.value,
prop_test$conf.int[1], prop_test$conf.int[2],
mean(rev_A), mean(rev_B),
t_rev$p.value,
t_rev$conf.int[1], t_rev$conf.int[2],
ifelse(prop_test$p.value < 0.05,
       "**Ship B.** The new checkout flow shows a statistically significant lift in conversion.",
       "**Do not ship.** The difference is not statistically significant.")
)

writeLines(summary_md, "reports/summary.md")

cat("Analysis complete.\n")
cat(sprintf("Conversion A=%.3f B=%.3f  p=%.4g\n", conv_A, conv_B, prop_test$p.value))
if (!has_ggplot) cat("(ggplot2 not installed - charts skipped; stats + summary still produced)\n")
